DROP TABLE "Order" CASCADE CONSTRAINTS;
DROP TABLE ProductFamily CASCADE CONSTRAINTS;
DROP TABLE BOM CASCADE CONSTRAINTS;
DROP TABLE RawMaterial CASCADE CONSTRAINTS;
DROP TABLE Component CASCADE CONSTRAINTS;
DROP TABLE CustomerType CASCADE CONSTRAINTS;
DROP TABLE BOO CASCADE CONSTRAINTS;
DROP TABLE Operation CASCADE CONSTRAINTS;
DROP TABLE WorkstationType CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Order_Product CASCADE CONSTRAINTS;
DROP TABLE Operation_WorkstationType CASCADE CONSTRAINTS;
DROP TABLE BOM_Component CASCADE CONSTRAINTS;
DROP TABLE BOM_RawMaterial CASCADE CONSTRAINTS;
DROP TABLE BOO_Operation CASCADE CONSTRAINTS;
CREATE TABLE "Order" (idOrder number(10) GENERATED AS IDENTITY, deliveryDate date NOT NULL, orderDate date NOT NULL, CustomeridCustomer number(10) NOT NULL, PRIMARY KEY (idOrder));
CREATE TABLE ProductFamily (idProductFamily number(10) GENERATED AS IDENTITY, name varchar2(255) NOT NULL, PRIMARY KEY (idProductFamily));
CREATE TABLE BOM (idBOM number(10) GENERATED AS IDENTITY, ProductidProduct number(10) NOT NULL, PRIMARY KEY (idBOM));
CREATE TABLE RawMaterial (idRawMaterial number(10) GENERATED AS IDENTITY, Description varchar2(255) NOT NULL, PRIMARY KEY (idRawMaterial));
CREATE TABLE Component (idComponent number(10) GENERATED AS IDENTITY, CodeComponent varchar2(255) NOT NULL UNIQUE, Description varchar2(255) NOT NULL, PRIMARY KEY (idComponent));
CREATE TABLE CustomerType (idCustomerType number(10) GENERATED AS IDENTITY, name varchar2(255) NOT NULL, PRIMARY KEY (idCustomerType));
CREATE TABLE BOO (IdBOO number(10) GENERATED AS IDENTITY, ProductFamilyidProductFamily number(10) NOT NULL, PRIMARY KEY (IdBOO));
CREATE TABLE Operation (idOperation number(10) GENERATED AS IDENTITY, description varchar2(255) NOT NULL, PRIMARY KEY (idOperation));
CREATE TABLE WorkstationType (idWorkstationType number(10) GENERATED AS IDENTITY, workstationCode varchar2(255) NOT NULL UNIQUE, name varchar2(255) NOT NULL, PRIMARY KEY (idWorkstationType));
CREATE TABLE Customer (idCustomer number(10) GENERATED AS IDENTITY, name varchar2(255) NOT NULL, VATIN varchar2(255) NOT NULL, address varchar2(255) NOT NULL, zipCode varchar2(255) NOT NULL, town varchar2(255) NOT NULL, country varchar2(255) NOT NULL, email varchar2(255) NOT NULL, phoneNumber number(12) NOT NULL, CustomerTypeidCustomerType number(10) NOT NULL, PRIMARY KEY (idCustomer));
CREATE TABLE Product (idProduct number(10) GENERATED AS IDENTITY, productCode varchar2(255) NOT NULL UNIQUE, name varchar2(255) NOT NULL, description varchar2(255) NOT NULL, ProductFamilyidProductFamily number(10) NOT NULL, PRIMARY KEY (idProduct));
CREATE TABLE Order_Product (OrderidOrder number(10) NOT NULL, ProductidProduct number(10) NOT NULL, quantity number(10) NOT NULL, PRIMARY KEY (OrderidOrder, ProductidProduct));
CREATE TABLE Operation_WorkstationType (OperationidOperation number(10) NOT NULL, WorkstationTypeidWorkstationType number(10) NOT NULL, PRIMARY KEY (OperationidOperation, WorkstationTypeidWorkstationType));
CREATE TABLE BOM_Component (BOMidBOM number(10) NOT NULL, ComponentidComponent number(10) NOT NULL, quantity number(10) NOT NULL, ProductidProduct number(10) NOT NULL, PRIMARY KEY (BOMidBOM, ComponentidComponent));
CREATE TABLE BOM_RawMaterial (BOMidBOM number(10) NOT NULL, RawMaterialidRawMaterial number(10) NOT NULL, quantity number(10) NOT NULL, PRIMARY KEY (BOMidBOM, RawMaterialidRawMaterial));
CREATE TABLE BOO_Operation (BOOIdBOO number(10) NOT NULL, OperationidOperation number(10) NOT NULL, operationSequence number(10) NOT NULL, PRIMARY KEY (BOOIdBOO, OperationidOperation));
ALTER TABLE Customer ADD CONSTRAINT FKCustomer327483 FOREIGN KEY (CustomerTypeidCustomerType) REFERENCES CustomerType (idCustomerType);
ALTER TABLE "Order" ADD CONSTRAINT FKOrder483930 FOREIGN KEY (CustomeridCustomer) REFERENCES Customer (idCustomer);
ALTER TABLE Order_Product ADD CONSTRAINT FKOrder_Prod186697 FOREIGN KEY (OrderidOrder) REFERENCES "Order" (idOrder);
ALTER TABLE Order_Product ADD CONSTRAINT FKOrder_Prod238195 FOREIGN KEY (ProductidProduct) REFERENCES Product (idProduct);
ALTER TABLE Product ADD CONSTRAINT FKProduct373764 FOREIGN KEY (ProductFamilyidProductFamily) REFERENCES ProductFamily (idProductFamily);
ALTER TABLE BOO ADD CONSTRAINT FKBOO483210 FOREIGN KEY (ProductFamilyidProductFamily) REFERENCES ProductFamily (idProductFamily);
ALTER TABLE Operation_WorkstationType ADD CONSTRAINT FKOperation_216418 FOREIGN KEY (OperationidOperation) REFERENCES Operation (idOperation);
ALTER TABLE Operation_WorkstationType ADD CONSTRAINT FKOperation_64928 FOREIGN KEY (WorkstationTypeidWorkstationType) REFERENCES WorkstationType (idWorkstationType);
ALTER TABLE BOM ADD CONSTRAINT FKBOM749439 FOREIGN KEY (ProductidProduct) REFERENCES Product (idProduct);
ALTER TABLE BOM_Component ADD CONSTRAINT FKBOM_Compon936606 FOREIGN KEY (BOMidBOM) REFERENCES BOM (idBOM);
ALTER TABLE BOM_Component ADD CONSTRAINT FKBOM_Compon394799 FOREIGN KEY (ComponentidComponent) REFERENCES Component (idComponent);
ALTER TABLE BOM_Component ADD CONSTRAINT FKBOM_Compon602038 FOREIGN KEY (ProductidProduct) REFERENCES Product (idProduct);
ALTER TABLE BOM_RawMaterial ADD CONSTRAINT FKBOM_RawMat625788 FOREIGN KEY (BOMidBOM) REFERENCES BOM (idBOM);
ALTER TABLE BOM_RawMaterial ADD CONSTRAINT FKBOM_RawMat91484 FOREIGN KEY (RawMaterialidRawMaterial) REFERENCES RawMaterial (idRawMaterial);
ALTER TABLE BOO_Operation ADD CONSTRAINT FKBOO_Operat203654 FOREIGN KEY (BOOIdBOO) REFERENCES BOO (IdBOO);
ALTER TABLE BOO_Operation ADD CONSTRAINT FKBOO_Operat620489 FOREIGN KEY (OperationidOperation) REFERENCES Operation (idOperation);
